### ISSUE TITLE
 Can I use images are not under copyright?

### ISSUE THREAD

**Issue by PavelNetesov** [Facepunch/RustWorkshop#109]
Hello, Garry. I want to ask you? You said that you need to create skins lishimet fotoshep and Rust. I have available and the game fotoshep Rust found online images that are not covered by copyright and made several skins! But some people have started to blame me for it! Tell me, Harry, I can use pictures from the Internet that do not have copyright or not?

**Comment by raycohaex** [comment]
There is not just copyright, there is also Creative Commons. Usually those images could be created by other people, and they can restrict their work to be used commercially. https://creativecommons.org/

You probaly won't be able to create hats which are red and have the mario icon on them. Or something similiar that is really stolen from other games. 
However, if you were talking about the "KFC" bucket, then i don't really have a clue.

Best is to grab your textures and images from websites which declare that all their stuff is free for commercial use. Well... ofcourse the best is to create stuff yourself. But im talking about
www.textures.com
and
www.episcura.com

Sorry if this information is not 100% accurate, i may have mistaken. But im pretty sure it is accurate. I hope this might help you out. Good luck with future skins

**I dont speak for facepunch though!**

**Comment by raycohaex** [comment]
> However, if you were talking about the "KFC" bucket, then i don't really have a clue.
What i mean is. So far i've seen it it's rather a mockup than the actual logo put on. I'm not sure but i think that is also wrong

**Comment by kfhammond** [comment]
If people can get [items accepted](http://steamcommunity.com/sharedfiles/filedetails/?id=803894027&searchtext=)  that use [blatantly copyrighted images](http://www.thefandom.net/wp-content/uploads/2016/04/497673361_preview_Punisher-Skull.jpg)... then who knows...

**Comment by RonRicoSuave** [comment]
I'd expect for the KFC bucket, the owner wouldn't care.  It's free advertising for a national restaurant chain in a game that lets you do hemp strains.  

Aside from that, I sell stock photography through Alamy.  If someone asked to use an image for a rust texture, I'd give them an original and rights, because I like the game.  OTOH if somebody jacked one from Alamy and *they* found out, you'd be looking at a potential treble damages lawsuit (at stock sale rates for your market / country / use case / resolution), and they are proactive about unauthorized use.   Nearly everything uploaded anywhere is automatically copyrighted, so you're best just asking the original photographer.  Considering the use case of these I'm guessing the photographers themselves would be willing to just share for the fun of it.

**Comment by StabbyMcStabface** [comment]
Hey KFHammond, first to clear things up about what was literally one of my FIRST attempts at a skin. I made the item for fun and didn't really expect it to be accepted, tbh. Just as hundreds of people have done with everything from Iron Man masks to Pokemon hats to Coca Cola T-shirts. As I said, it was one of my first skins and I was still learning/trying things out; I wasn't thinking about much else, and, when Garry added it I was really surprised. When he removed it (literally hours later) I completely understood and accepted that. I also later reached out to Marvel licensing to ASK them if I COULD get permission to use it (just in case Garry even wanted to put it back up) but they never replied. 

Had I not called it Punishment Mask and just went with the 4 Deuces skull (which is the SEAL variation of the Punisher logo that Marvel adopted in the late 90s - the original logo is a blocky bold normal "skull") when originally submitted it would probably have been even less of an issue. You obviously seem extra perturbed about it and the wording of your comment seems to paint me as some sort of hack/thief, but one look at the over 60 items on my workshop I've made since will show you that this isn't the case.
