### ISSUE TITLE
A couple of questions skins related

### ISSUE THREAD

**Issue by elfideorubio** [Facepunch/RustWorkshop#45]
Do the artist see any money from the crates or marketplace?

Some of the items from last week were removed from the store and added to the crates, what's the process of chosing certain items to appear in a crate instead of the store itself?

If two artist reach the same idea ( which is likely ) and they have similar rates, how would you decide which one to add to the game?

There seems to be a lot of issues with copyrated material, what is technically legal in this sense? for instance if I take a texture off the internet and I edited to meet my demands is that inside legality? ( obviously without water marks )

**Comment by Kamiling** [comment]
I have the same doubt

**Comment by garrynewman** [comment]
https://github.com/Facepunch/RustWorkshop/wiki/FAQ

**Comment by Kamiling** [comment]
You really want people to continue making skins when you're just going to put them into bags without the creators receiving any compensation for their work?

**Comment by garrynewman** [comment]
This is how the economy works, how do you imagine it working?

**Comment by Kamiling** [comment]
Maybe on a old XIX century mercantilism.

**Comment by raycohaex** [comment]
The csgo economy does work this way, just because you don't want keys doesn't mean that it is how the economy works. Please listen to the content creators too. genually disappointedin in you guys

**Comment by garrynewman** [comment]
I'm listening, what do you want, how do you imagine it working?

**Comment by raycohaex** [comment]
You've stated "No. This is something Valve are working on. It's the reason "keys" exist in other games - which is not something we want in Rust." which is something you don't want as a company, which leaves us as content creators in the dark.

**Comment by raycohaex** [comment]
We as content creators would be more than happy with the keys, so we get revenue from our skins. But you guys don't want it, and you are listening?

**Comment by garrynewman** [comment]
I'm saying we don't want to charge people $5 for a key to open a box that gets random dropped into their inventory. You want that?

**Comment by Kamiling** [comment]
The store already works fine. I don't know what's the point of the bags

**Comment by raycohaex** [comment]
If i want a certain csgo skin i buy it from the market if im unlucky with cases. There are also no specific skins i would want in rust, just any skin is fine.  Yes this will generate mixed feeling for the community. But you can be creative with the bags. I want a knife in csgo too but what the point of making it a buyable item, it won't be rare it just depends on how much money you have in your wallet.

**Comment by raycohaex** [comment]
Again, it's a mixed situation and you guys proven to do good for the game so far, i just hope you come up with something else than cutting down the revenue for skin creators after a while.

**Comment by garrynewman** [comment]
The point of bags is to give people a reason to recycle their items, so that when they want to sell something on marketplace they're not selling for $0.01. Without bags everything eventually gets to that price.

I don't like the idea of charging people for a random chance of getting something they want. I've got no doubt it would make a lot more money than the current way, but it feels wrong.

The skin lifecycle, as I see it.
1. Sells for a limited period on item store. People know it's a limited period so they buy it. Artists win.
2. People who bought sell for more on marketplace, because the item is no longer for sale. Buyers win.
3. People who don't spend money recycle items from drops, get item for free. Players win.

I get that you feel like it sucks that artists only see money on stage one, and I get that - I'll try to make it more clear that this is how it works.

**Comment by raycohaex** [comment]
Alright, curious to see how it turns out, good luck!

**Comment by Kamiling** [comment]
One week old skin removed from store too. "limited period". 

How long is the "limited period"?

**Comment by bokatau** [comment]
Its very bad idea.

**Comment by bokatau** [comment]
If in the process of "approval" was justice and the linearity - I'd worked so, but now the game can get into crap, and normal "long" work remain invisible. People who spend a day on the development of things does not want to waste their time and risk for the sake of "a couple of days" in the store.

A person can do something good and it will not notice
The game can be added something serious deficiencies, such as crap:
http://steamcommunity-a.akamaihd.net/economy/image/rtOnLXYSD-u65eusOk-nO4hCpUCJo2NbCxc2U4Y51MLNQ5Hz3URG1UJcBu0sv2Ko-M1Zj0mvYmKzVOblhE3jZjuDtDkHlikYyUNwwY7RwQ7H6Q/512fx512f

**Comment by Kamiling** [comment]
![tribal-skull-tattoo-from-frontal-view_91-8282](https://cloud.githubusercontent.com/assets/23229044/20400867/4605228c-acd5-11e6-9ced-225f4098d2d2.jpg)
This is the skin

**Comment by bokatau** [comment]
Man, the creator of the skin just put a picture on top of everything else, there is even a layer of normal is not changed, she seemed to float in the air above the mask. More and pushed it so terribly that at the edges of the image which the terrible glare. I think it was done about 5 minutes.

But in general, he just stole my job!

I did my mask about 3 days: http://steamcommunity.com/sharedfiles/filedetails/?id=788431729
Yes, it may be less popular (actually not). But it's made with love for the game! With love to detail!
It not accepted! How???

Do I want to continue to try and do something that would be good then someone did shit / stole my job and went to the store? If it is for "limited period" my answer is NO.

**Comment by raycohaex** [comment]
I don't care if my skin goes extinct after a while, but im creating quite a few skins. And it was so hard for me to get a skin in the market. I'd be so disappointed if it gets removed soon, if skins are accepted more likely i wouldn't really care. But it's way too hard eventhough my votes are 80% possitive most of the times i only get up to 300 votes at max.

**Comment by raycohaex** [comment]
yet the item store can't be spammed full of skins which is understandable too. If there is much more diversity to pick from then the chance of your skin being sold is much lower. But right now it's best to give garry some time to explain it

**Comment by bokatau** [comment]
I think that we should not "clean" those jobs that are in demand, that's all. This rule can work with those works that are not popular - it would be logical.

This motivated to do good work and improve old work.

**Comment by DutchAllians** [comment]
Garry wont combining keys with skins work? so people can choose to buy a 8$ skin(from the rust store) or a X$ key, since the skins are there for a limited time anyway. If people want a specific skin they can buy it for "a limited time". So people can atleast choose if they wanna gamble or buy

**Comment by SGTSolj** [comment]
I think the very least Facepunch could do is add a section in today's DevBlog to explain to the skin creators what is going on and why their skins are disappearing from the Store. While it may mean nothing to you Garry, for some of these creators the skins represent a lot of hard work and dedication to YOUR game and by removing them without any explanation makes your development team seem very irresponsible.

**Comment by garrynewman** [comment]
Which item are you talking about specifically?

**Comment by bokatau** [comment]
I think here you can to get feedback from the community
https://www.youtube.com/watch?v=Wag5410poGw

**Comment by SGTSolj** [comment]
I don't understand your question, you didn't really give me much to build off of discussion wise. A lot of the skins creators are against this change you've briefly highlighted because there's little to no information out explaining what's going to happen even though you've already started to implement the changes. If you want to have a flourishing micro-economy built around skins you need to have a positive relationship with the people that make those skins. All these people want to know what's going to happen with their skins, how long they're going to be available, how much money is "too much money", and how much money they're going to lose by changing to this bag system you're so fixed on implementing. By keeping them all in the dark while making the changes anyways, it shows a gross level of irresponsibility and will cause more skin creators to go back to CSGO because at least there they're being compensated.

**Comment by DevinWatson** [comment]
I don't have an issue with the way it works now. Sales of the item basically died after one week anyways. I think there could be some more clarity around the items only being in the store for a limited time.
Would it be nice to get a portion of the 12% Valve takes out of the market sales? Sure, but I realize that's not how it works right now.

**Comment by elfideorubio** [comment]
I think he refers to these:
Big Grin Metal Facemask, Ranger's Vest, Metal chest plate forest camo, Glowing skull facemask.

they were only in for a week or so

**Comment by garrynewman** [comment]
@SGTSolj 

So a couple of points.
- This isn't a change. We've retired skins in the past. The only difference now is that there's a way for people to still get them, if that's the problem, we can change that for sure.
- Skin makers aren't going to lose any money here - because this is how it always has been

If skin makers aren't having fun making skins for Rust - they shouldn't bother. They're always going to make more money making TF2/CS:GO/DOTA skins - if that's what's important.

If you want more answers you need to stop talking for the whole community and be more specific with your problems.

**Comment by raycohaex** [comment]
Making skins is fun, but the current situation isn't. Also TF/CS:GO/DOTA skins are even more crowded and the chance you succeed there is much less likely than here in rust. If it's not about money then why not allow mods like in garry's mod.

**Comment by garrynewman** [comment]
It is about making money, it's just not about making the money for us. It's for the community.

**Comment by Kamiling** [comment]
Theres 114 skins added to Rust..  52 are currently on the store.

And a few days ago, over 40 was removed at the same time.
If that's true... leave the store. The bags are good yes, but is easier just buy the skin than buy 100 other skins to craft a bag.

**Comment by garrynewman** [comment]
We hadn't touched the skins for months before that - don't be surprised that things are happening now.

**Comment by raycohaex** [comment]
But still, its very very hard to get your skin in rust. But it seems to be easy to lose it? (referring to the skins that were removed within a week, not the ones that were removed after a year)

**Comment by DevinWatson** [comment]
Making skins is just a fun hobby for me. I was more excited to have a skin in the game than actually making any money off of it. I really don't see an issue with the current system. If you are so concerned about your skins being "stolen" or w/e via these bags you're in this for the wrong reason. Having your item in the store for a week should be more than enough revenue wise.

**Comment by raycohaex** [comment]
What is "more than enough revenue" it is different for everyone

**Comment by garrynewman** [comment]
The skins that were removed after a week made over $10,000 - that feels like enough for one item. It feels like it's served its purpose and can be given to the community from that point.

**Comment by bokatau** [comment]
Well, it's more or less justifiable limit. In fact, there is no reason for its existence, but it looks right.
Most deprived of income - is of course not very good, perhaps it would be necessary to leave some minimal money can $ 5 a day for one job or something like that. It would have comforted people. Simply "throwing" it's bad.

**Comment by raycohaex** [comment]
The reason im upset is because it took me alot of attempts to get the skin ingame, now i succeeded and then it will get stuffed in a bag within "limited time". If skins are accepted much more frequent then alright, but atm it's random since there is a lack of votes?

**Comment by garrynewman** [comment]
We're adding new skins every week. We could stock every skin forever - but having a skin on page 23 of 40 doesn't help anyone. No-one is going to buy it.

Everyone complaining that we didn't sell their skin properly isn't something I'm going to put up with. At that point this stops being fun and gets shut down.

**Comment by Kamiling** [comment]
I need do admit it... its true, every week skins get in-game.

**Comment by DevinWatson** [comment]
Christ ya'll are creating a lot of un-needed drama over nothing. The system as it stands keeps the item store fresh with new items every week. It allows a lot of creators to have items in game. Just because your item is removed from the store after a week doesn't mean your item is "lost" and all your hard work for nothing. You item still lives on in the game which is pretty cool, and you made some money off of it too.

If you don't think a week is long enough in the store just look at this, sales are barely even registering at the end of the week. If that's not good enough for you you're just being greedy.

![screen shot 2016-11-17 at 2 54 18 pm](https://cloud.githubusercontent.com/assets/1735588/20405118/cfb43d24-acd5-11e6-8061-8cb177a8015b.png)

There currently isn't a system in place for any creators to get revenue from the bags besides keys which I think we can all agree is a terrible idea. So if this is really such an issue for you go get hired at Valve and fix it yourself, otherwise quit your bitching. Lastly the revenue from market sale fees is an order of magnitude smaller than what you make on the Rust store; like not even worth the time you've spent complaining about this.

**Comment by bokatau** [comment]
@garrynewman "We're adding new skins every week. We could stock every skin forever - but having a skin on page 23 of 40 doesn't help anyone. No-one is going to buy it."

This is not true, I can sell them on their own resources, using a direct link, for example. Some of the skins will be popular and "never not go out," and there are many reasons why this is not true. A person can see the skin at someone and say - hey man I want to buy the same, and he will respond to him, "Go f, it no longer exists"

PS - I'm not saying that Garry was wrong, he had the right attitude, I'm just saying that you might have overlooked.

**Comment by Krovv** [comment]
Im ok with keeping the item store fresh
Maybe you coud add like 6 skins per week and "revive" one random old skin for a week, every week, so you can maintain a fixed amount of skins every week and give the opportunity for people to acquire old skins for a limited time

**Comment by bokatau** [comment]
@DevinWatson "If you don't think a week is long enough in the store just look at this, sales are barely even registering at the end of the week. If that's not good enough for you you're just being greedy."

Some jobs may show a different result

"Just because your item is removed from the store after a week doesn't mean your item is "lost" and all your hard work for nothing. You item still lives on in the game which is pretty cool, and you made some money off of it too."

There simply there is a speech that the artists want have paid for "bag" and trading platform,  every walk around it.... I think it might be a very small percentage, so that would be all satisfied.

**Comment by bokatau** [comment]
@garrynewman You know, the art of such a thing, which can not become outdated. The older a thing is the better it is. Of course, not always, some of the work, "forget" and such work can safely clean up! No one would even not say a word if you cleaned out "forgotten" work, but you want to destroy everything!

If in the "Hermitage" said: It seems that these pictures are already costs one million dollars, it's time to throw them fck, while the hang here for over a week, remove them too! Let's take a more modern art! - It would be strange.

Remove irrelevant, why should remove what in demand?
You are talking about the economy, this would have been the economy.

**Comment by sgtdolphin** [comment]
I have some skins that are not being bought much anymore, the demand for them isn't there. Weather that's because there are better skins out there now or they aren't being seen. I understand them being removed from the store and put into legacy boxes or whatever. I would like as krov said.

> Maybe you coud add like 6 skins per week and "revive" one random old skin for a week, every week.

I think if you are going to add stuff that is limited you should state it in the store, creators and purchasers would be confused if not I think.

**Comment by bokatau** [comment]
> Maybe you coud add like 6 skins per week and "revive" one random old skin for a week, every week.

Delete random things is not a good idea because they can be good and necessary, but can be removed "forgotten" and unclaimed.

**Comment by SGTSolj** [comment]
> I think if you are going to add stuff that is limited you should state it in the store, creators and purchasers would be confused if not I think.

This is precisely what I said in my first post in this discussion, people just want to know what's going on and how it's going to effect them. If you don't tell people that the skins are going to be limited or tell the creators that their skins are going to be available until they reach a certain "cap" then they're going to react negatively to anything you do.

> I think the very least Facepunch could do is add a section in today's DevBlog to explain to the skin creators what is going on and why their skins are disappearing from the Store.

_EDIT_ This was a comment left on the video I made, I think it brings up a lot of good points. 

> Satire 26 minutes ago
> Keeping the market fresh is necessary. Adding new skins revitalizes the community and makes more sales for the game and skins. I don't think the limit to the lifespan of a skin should be how much money it makes, but rather how many units it sells comparative to its set price. You want to keep the value of "high value" items such as the Glowing Mask, so you don't want to sell too many as individual inflation will incur. This could be a selling point, such as "Limited sales" or "Only 5,000 available" and people will flock to it. Maybe have new skins only available on the rust store at first to set a solid price AND have the creators make some money :)﻿

I like this comment for a lot of reasons, but even with the ideas presented in Satire's comment it all comes down to communicating with not only the overall Rust Community but the Skin Creator Community as well.

**Comment by Subza** [comment]
You guys like shitty misused memes?
![5169527](https://cloud.githubusercontent.com/assets/13123653/20411000/c03b6720-ad73-11e6-99fc-b7f498f68f0e.jpg)

**Comment by bokatau** [comment]
I just like debate

**Comment by RedsWorkshop** [comment]
Hey garry, its me red. The guy what help you out with the workshop together with starpluck. 
Is it possible to talk to you about the workshop for rust? I know your intention was good, we allready talked about things like that if you remember (Milhitos AK). I think we could find together a solution. I do content for 4 years for the workshop and got skins in csgo. Please take some time and talk to me, im in touch with a lot of content creators all arround the workshop, and im sure together we find a solution for that problem. My steam acc: http://steamcommunity.com/id/TeamRed/

Love ya, 
red :D

**Comment by garrynewman** [comment]
Your friend list is full, shoot me an email at garrynewman@gmail.com

**Comment by MilhoFrito** [comment]
Hey Garry, I'm now having this error on console when opening V2 skins.
I think I will upload the old ones as new ones and loosing all votes unfortunately.

<a href="https://gyazo.com/c9b7eb5c61877f143efaa8a35486b639"><img src="https://i.gyazo.com/c9b7eb5c61877f143efaa8a35486b639.png" alt="https://gyazo.com/c9b7eb5c61877f143efaa8a35486b639" width="509"/></a>

Some feedback after you removed some skins yesterday.. my sales increased 41% from Wednesday to Thursday.. maybe coincidence or not, but I'm sure it makes the remaining skins more visible.

Milho Frito

**Comment by garrynewman** [comment]
Please start a new issue for this stuff - I'll fix it. Switch to the staging branch in the meantime, I'll get a fix up on there.
