### ISSUE TITLE
Hide count Like, Dislike and source file in game WorkShop

### ISSUE THREAD

**Issue by bokatau** [Facepunch/RustWorkshop#49]
Hello, sorry for bad english.

Please, hide count Like, Dislike and source file in game WorkShop
Now anyone who sees the number of likes and dislike. That contradicts of Steam policy regarding this (that is information for authors) and affects the person's opinion of the work.

Another problem is that anyone can open someone else's project and download it layers.
Edit mode and view mode why do is linked "drop-down" menu. That's good, but I would not want that to my achievements have been publicly available. Now the workshop many children who dislike everything and stealing other people's work, it gives bathert. I cry every night.

Please fix it Т_Т

**Comment by Subza** [comment]
"Yeah it's intentional. We can all learn from each other. We could get rid of the export feature - but you can download anything and view its contents anyway. So why try to hide it?" -Garry

Personally i think it's pretty cool to be able to see others work. I ran into a few problems working on the emission layer and it was nice to be able to see how others went about it, it saved me a lot of time and generally made my submission come out better, and as Garry said you would be able to see other stuff anyway so why make it hard.

**Comment by bokatau** [comment]
> We can all learn from each other.

We are with you, adequate and adults - understand it.
I am very happy about it, can watch the work of such masters as xstab and learn.
But the community is not completely out like us.

Now, in the workshop a bunch of schoolboys and young authors haters who steal you work, unlike you and etc... They can just take the items you developed, attach them to camouflage and publish. And if your job was lost in the attacks competitors his work with camouflage will have more rights.


Or do you think that someone will be find original?
Let us then make it possible complaints if your rights have been violated.
Where it will be possible to write such a complaint? Nowhere.
More advanced workshops given for this ban.

I say this because faced with the theft more than once.
The problem is young, but these complaints will only become more frequent.

> "But you can download anything and view its contents anyway. So why try to hide it?"

Those people who can do it without **your help** - that would be smart enough not to do it.
And those who do this - can only camouflage paint. And for them it will be a serious problem.
